[package]
name = "server"
version = "0.1.0"
authors = ["Samuel Sleight <samuel.sleight@gmail.com>"]
edition = "2018"

[dependencies]
lobby = { path = "../lobby" }
shared = { path = "../shared" }
vec_map = "*"
